# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v4.6.0
   hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-yaml
    - id: destroyed-symlinks
    - id: end-of-file-fixer
    - id: fix-byte-order-marker
    - id: mixed-line-ending
      args: ['--fix=lf']
    #- id: no-commit-to-branch
    #  args: ['--branch', 'main']
    - id: trailing-whitespace
 - repo: https://github.com/Lucas-C/pre-commit-hooks
   rev: v1.5.5
   hooks:
     - id: remove-tabs
     - id: remove-crlf
     - id: forbid-tabs
     - id: forbid-crlf
